---
name: CI
"on":
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt
          pip install --upgrade ruff black pytest-cov
      - name: Ruff lint
        run: ruff check .
      - name: Black formatting check
        run: |
          black --check .
      - name: Run tests with coverage
        run: |
          pytest -v --cov=src --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: coverage.xml
      - name: Set up Node
        if: hashFiles('src/frontend/package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json
      - name: Run frontend tests
        if: hashFiles('src/frontend/package.json') != ''
        working-directory: src/frontend
        run: npm ci && npm test -- --ci
